spring.application.name=fifa_world_cup_2026

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/fifaworldcup?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

# Resource bundles (i18n)
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8

spring.profiles.active=dev

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Puntensysteem
score.exact.points=10
score.winner.points=5
score.bonus.exclusive.exact=3
score.bonus.exclusive.winner=2